package com.example.demo.Controllers;

import com.example.demo.Models.Event;
import com.example.demo.Services.EventService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/events")
@Tag(name = "Events", description = "Operations related to event management")
public class EventController {

    private final EventService service;

    public EventController(EventService service) {
        this.service = service;
    }

    @Operation(
            summary = "Get all events (paginated)",
            description = "Returns a paginated and sortable list of events. " +
                    "Use query params: ?page=0&size=10&sort=name,asc"
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Page of events returned"),
            @ApiResponse(responseCode = "204", description = "No events found")
    })
    @GetMapping
    public ResponseEntity<Page<Event>> findAll(
            @Parameter(description = "Filter by name (optional)")
            @RequestParam(required = false) String name,
            @ParameterObject
            @PageableDefault(size = 10, sort = "name", direction = Sort.Direction.ASC)
            Pageable pageable) {

        Page<Event> result = (name != null && !name.isBlank())
                ? service.findByName(name, pageable)
                : service.findAll(pageable);

        if (result.isEmpty()) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get event by ID", description = "Returns the event matching the given ID")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Event found"),
            @ApiResponse(responseCode = "404", description = "Event not found")
    })
    @GetMapping("/{id}")
    public ResponseEntity<Event> findById(@PathVariable Long id) {
        Event event = service.findById(id); // lanza 404 si no existe
        return ResponseEntity.ok(event);
    }

    @Operation(
            summary = "Create a new event",
            description = "Creates a new event. The ID is auto-generated by the database."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Event successfully created"),
            @ApiResponse(responseCode = "400", description = "Validation failed — missing or invalid fields")
    })
    @PostMapping
    public ResponseEntity<Event> create(@Valid @RequestBody Event event) {
        Event created = service.create(event);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @Operation(summary = "Update an existing event", description = "Updates name and description of the event with the given ID")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Event successfully updated"),
            @ApiResponse(responseCode = "400", description = "Validation failed"),
            @ApiResponse(responseCode = "404", description = "Event not found")
    })
    @PutMapping("/{id}")
    public ResponseEntity<Event> update(@PathVariable Long id, @Valid @RequestBody Event updatedEvent) {
        Event updated = service.update(id, updatedEvent);
        return ResponseEntity.ok(updated);
    }

    @Operation(summary = "Delete an event", description = "Permanently deletes the event with the given ID")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Event successfully deleted"),
            @ApiResponse(responseCode = "404", description = "Event not found")
    })
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.delete(id);
        return ResponseEntity.noContent().build(); // 204 No Content
    }
}