package com.example.demo.Controllers;

import com.example.demo.Models.Venues;
import com.example.demo.Services.VenuesService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/venues")
@Tag(name = "Venues", description = "Operations related to venue management")
public class VenuesController {

    private final VenuesService service;

    public VenuesController(VenuesService service) {
        this.service = service;
    }

    @Operation(
            summary = "Get all venues (paginated)",
            description = "Returns a paginated and sortable list of venues. " +
                    "Use query params: ?page=0&size=10&sort=name,asc"
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Page of venues returned"),
            @ApiResponse(responseCode = "204", description = "No venues found")
    })
    @GetMapping
    public ResponseEntity<Page<Venues>> findAll(
            @Parameter(description = "Filter by name (optional)")
            @RequestParam(required = false) String name,
            @ParameterObject
            @PageableDefault(size = 10, sort = "name", direction = Sort.Direction.ASC)
            Pageable pageable) {

        Page<Venues> result = (name != null && !name.isBlank())
                ? service.findByName(name, pageable)
                : service.findAll(pageable);

        if (result.isEmpty()) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get venue by ID", description = "Returns the venue matching the given ID")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Venue found"),
            @ApiResponse(responseCode = "404", description = "Venue not found")
    })
    @GetMapping("/{id}")
    public ResponseEntity<Venues> findById(@PathVariable Long id) {
        Venues venue = service.findById(id);
        return ResponseEntity.ok(venue);
    }

    @Operation(
            summary = "Create a new venue",
            description = "Creates a new venue. The ID is auto-generated by the database."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Venue successfully created"),
            @ApiResponse(responseCode = "400", description = "Validation failed — missing or invalid fields")
    })
    @PostMapping
    public ResponseEntity<Venues> create(@Valid @RequestBody Venues venues) {
        Venues created = service.create(venues);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @Operation(summary = "Update an existing venue", description = "Updates name and address of the venue with the given ID")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Venue successfully updated"),
            @ApiResponse(responseCode = "400", description = "Validation failed"),
            @ApiResponse(responseCode = "404", description = "Venue not found")
    })
    @PutMapping("/{id}")
    public ResponseEntity<Venues> update(@PathVariable Long id, @Valid @RequestBody Venues updatedVenues) {
        Venues updated = service.update(id, updatedVenues);
        return ResponseEntity.ok(updated);
    }

    @Operation(summary = "Delete a venue", description = "Permanently deletes the venue with the given ID")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Venue successfully deleted"),
            @ApiResponse(responseCode = "404", description = "Venue not found")
    })
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.delete(id);
        return ResponseEntity.noContent().build(); // 204 No Content
    }
}