# BASE DE DATOS H2 PERSISTENTE
spring.datasource.url=jdbc:h2:file:./data/eventifydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AUDITORIA SQL: muestra los valores reales de los parametros (?1, ?2...)
# Sin esto: WHERE v.city = ?
# Con esto:  binding [1] as VARCHAR - [Medellin]
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false


# CONSOLA H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SWAGGER UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.paths-to-exclude=/admin/**

# THYMELEAF
spring.thymeleaf.prefix=classpath:/template/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
